name: Q1 Workflow

on: [push]
permissions:
  contents: write

jobs:
  question-1ds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Créer le fichier Q1_archive_README.md (copie de README.md)
      - name: Creer Q1_archive_README.md
        run: |
          cp README.md Q1_archive_README.md

      # Configurer Git
      - name: Config Git
        run: |
          git config --global user.name ShantiLKael
          git config --global user.email shantil_ytb@outlook.com

      # Ajouter et pousser le nouveau fichier sur la branche
      - name: Commit et push
        run: |
          git add Q1_archive_README.md
          git commit -m "Add Q1_archive_README.md"
          git push
