name: Q5 Workflow

on: [push]
permissions:
  contents: write

jobs:
  question-5ds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Créer le fichier Q5_archive_date.txt
      - name: Creer Q5_archive_date.txt
        run: |
          echo "Nom et Prénom : Ashanti NJANJA" > Q5_archive_date.txt
          echo "Date et heure d'exécution : $(date '+%Y-%m-%d à %H:%M:%S')" >> Q5_archive_date.txt
          cat Q5.java >> Q5_archive_date.txt

      # Configurer Git
      - name: Config Git
        run: |
          git config --global user.name ShantiLKael
          git config --global user.email shantil_ytb@outlook.com

      # Ajouter et pousser le nouveau fichier
      - name: Commit et push
        run: |
          git add Q5_archive_date.txt
          git commit -m "Add Q5_archive_date.txt"
          git push
